# Azure Pipelines configuration for deployment
trigger:
  branches:
    include:
      - main
pr: none

jobs:
  - job: Test
    displayName: 'Run Tests'
    pool:
      vmImage: 'ubuntu-latest'
    environment: testing
    variables:
      MONGODB_CLUSTER_ADDRESS: 'cluster0.yhupnie.mongodb.net'
      MONGODB_USERNAME: '$(MONGODB_USERNAME)'
      MONGODB_PASSWORD: '$(MONGODB_PASSWORD)'
      PORT: '8080'
    steps:
      - checkout: self
        displayName: 'Get Code'
      - task: Cache@2
        displayName: 'Cache dependencies'
        inputs:
          key: 'npm | "$(Agent.OS)" | package-lock.json'
          path: '$(HOME)/.npm'
          cacheHitVar: 'CACHE_RESTORED'
      - script: npm ci
        displayName: 'Install dependencies'
      - script: npm start & npx wait-on http://127.0.0.1:$(PORT)
        displayName: 'Run server'
      - script: npm test
        displayName: 'Run tests'
      - script: echo "MONGODB_USERNAME $(MONGODB_USERNAME)"
        displayName: 'Output information'

  - job: Deploy
    displayName: 'Deploy'
    dependsOn: Test
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
          echo "MONGODB_USERNAME $(MONGODB_USERNAME)"
          echo "MONGODB_DB_NAME $(MONGODB_DB_NAME)"
        displayName: 'Output information'